### ISSUE TITLE
Don't use tables to layout the cards, look into using flexbox instead

### ISSUE THREAD

**Issue by chrzrdx** [JemimaSadhika/edyst-s19-choose-a-pokemon#1]
https://github.com/JemimaSadhika/edyst-s19-choose-a-pokemon/blob/902a92dcc506f3858d83d4cfc62e188030bb0af0/frontend/index.html#L79

https://internetingishard.com/html-and-css/flexbox/

**Comment by JemimaSadhika** [comment]
Updated the code using flexbox instead of tables.
