### ISSUE TITLE
Use virtual environments for python projects, update your README to reflect this

### ISSUE THREAD

**Issue by chrzrdx** [JemimaSadhika/edyst-s19-choose-a-pokemon#2]
Some users may have a different version of python, and also may be apprehensive of installing python packages globally. Go through a tutorial on "virtualenv" to structure your application better.

**Comment by kvsrinivas91** [comment]
This can solved by creating a virtual environment in the backend directory.
command is 'virtualenv venv'
Then add the file name 'venv' to .gitignore file.

**Comment by JemimaSadhika** [comment]
Updated the README.md to include virtualenv.
